config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews, only: %i[new create]
  end

  resources :reviews, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  CATEGORIES = %w[chinese italian japanese french belgian]
  validates :name, :address, :phone_number, :category, presence: true
  has_many :reviews, dependent: :destroy
  validates :category, inclusion: { in: CATEGORIES, allow_nil: false }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, :rating, presence: true
  validates :rating, inclusion: { in: [0, 1, 2, 3, 4, 5],  allow_nil: false }, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: %i[show edit update destroy]
  # before_action :set_review, only: %i[destroy]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def show; end

  def update
    @restaurant.update(restaurant_params)
    redirect_to restaurants_path
  end

  def destroy
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  # def set_review
  #   @review = Review.find(params[:review_id])
  # end

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category, :reviews)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant, only: %i[new create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @restaurant = @review.restaurant
    @review.destroy
    redirect_to restaurant_path(@restaurant)
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<div class="container">
  <%= simple_form_for @restaurant do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
    <%= f.button :submit, "Incluir Restaurante", class: "btn btn-success mt-3"%>
  <% end %>
</div>
<div class="text-center py-3"> 
  <%=link_to 'volver a restaurantes', restaurants_path, class: 'btn btn-primary'%>
</div>

app/views/restaurants/edit.html.erb
<div>
  <h1>Editar Restaurant</h1>
</div>
<%= render "form", restaurant: @restaurant %>

app/views/restaurants/index.html.erb
  <h1 class="py-5"> TODOS LOS RESTAURANTES </h1>
<div class="container mt-4 d-flex justify-content-evenly">
  <% @restaurants.each do |restaurant| %>
    <div class="card mb-3" style="width: 18rem;">
      <ul class="list-group list-group-flush">
        <li class="list-group-item"> <strong>Nombre: </strong><%= link_to restaurant.name, restaurant_path(restaurant) %></li>
        <li class="list-group-item"> <strong>Direccion: </strong><%=restaurant.address %></li>
        <li class="list-group-item"> <strong>Contacto: </strong><%=restaurant.phone_number %></li>
        <li class="list-group-item"> <strong>Categoria: </strong><%=restaurant.category %></li>
        <li class="list-group-item"> <strong>Opiniones: </strong><%=restaurant.reviews.count %></li>
      </ul>
    </div>    
  <% end %>
</div>
<div class="container">
  <div class="text-center py-3">
    <%= link_to 'Incluir otro restaurant', new_restaurant_path, class: 'btn btn-primary'%>
  </div>
</div>

app/views/restaurants/new.html.erb
<h1> NUEVO RESTAURANTE </h1>

<%=link_to 'volver a restaurantes', restaurants_path%>

app/views/restaurants/show.html.erb
<div class="container py-5">
  <div class="card">
    <div class="card-header">
      <%= @restaurant.name%>
    </div>
    <div class="card-body">
      <h5 class="card-title"><span class="link-primary">Direccion: </span> <%= @restaurant.address.capitalize %></h5>
      <h5 class="card-title"><span class="link-primary">Contacto: </span><%= @restaurant.phone_number %></h5>
      <h5 class="card-title"><span class="link-primary">Categoria: </span><%= @restaurant.category.capitalize %></h5>
      <ul class="list-group mb-3">
        <% @restaurant.reviews.each do |review| %>
          <li class="list-group-item"><%= review.content %></li>
          <li class="list-group-item"><%= review.rating %> Stars</li>
          <%= link_to "Remove", review_path(review), method: :delete, data: { confirm: "Are you sure?" } %>
        <% end %>
      </ul>
      <div class="border text-center">
        <%= link_to 'Eliminar', restaurant_path(@restaurant), method: :delete %> || <%= link_to 'Editar', edit_restaurant_path%> || <%= link_to 'Home', restaurants_path%> || <%= link_to 'Leave a review', new_restaurant_review_path(@restaurant) %>
      <div>
    </div>
  </div>
</div>  

app/views/reviews/new.html.erb
<%= simple_form_for [ @restaurant, @review ] do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

<%= link_to 'Home', restaurants_path%> 